In [1]:
import numpy as np

In [4]:
arr = np.array([8,12,9,3,7])

In [5]:
arr

array([ 8, 12,  9,  3,  7])

In [6]:
print(arr)

[ 8 12  9  3  7]


In [7]:
mat = np.array([[8,9,13,16,7],[9,12,7,3,4]])

In [8]:
mat

array([[ 8,  9, 13, 16,  7],
       [ 9, 12,  7,  3,  4]])

In [9]:
arr

array([ 8, 12,  9,  3,  7])

In [10]:
arr[0]

np.int64(8)

In [11]:
print(arr[0])

8


In [12]:
print(mat[1][4])

4


In [15]:
a = np.zeros(2)

In [16]:
a

array([0., 0.])

In [17]:
print(a)

[0. 0.]


In [19]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
b = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
a = np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
b = np.ones([2,3])
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
nums = np.arange(2,100,2)
print(nums)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [34]:
arr  = np.array([9,12,3,9,13])
print(arr[1:4])

[12  3  9]


In [42]:
mat = np.array([[8,9,13,16,7],[9,12,7,3,4]])
print(mat)

[[ 8  9 13 16  7]
 [ 9 12  7  3  4]]


In [44]:
print(mat[0:1,2:4])

[[13 16]]


In [45]:
print(mat[0:2,1:3])

[[ 9 13]
 [12  7]]


In [46]:
print(mat[:,3])

[16  3]


In [47]:
print(mat[1,:])

[ 9 12  7  3  4]


In [48]:
print(mat[:,2:4])

[[13 16]
 [ 7  3]]


In [50]:
import random
a = np.random.randint(20,50,5)
b = np.random.randint(10,40,5)
print(a)
print(b)

[25 32 25 34 21]
[30 36 39 32 12]


In [51]:
print(a*2)

[50 64 50 68 42]


In [52]:
print(a+100)

[125 132 125 134 121]


In [55]:
print(a//2)

[12 16 12 17 10]


In [56]:
print(a+b)

[55 68 64 66 33]


In [57]:
print(a*b)

[ 750 1152  975 1088  252]


In [58]:
a = np.random.randint(1,50,8)
print(a)

[35 24 42 24 44 12 10  4]


In [63]:
print(np.sum(a))

195


In [64]:
print(np.max(a))
print(np.min(a))

44
4


In [65]:
print(np.mean(a))

24.375


In [71]:
print(np.sort(a))
print(np.sort(a)[::-1])
print(a)

[ 4 10 12 24 24 35 42 44]
[44 42 35 24 24 12 10  4]
[35 24 42 24 44 12 10  4]


In [73]:
print(a)

[35 24 42 24 44 12 10  4]


In [75]:
print(a>25)

[ True False  True False  True False False False]


In [77]:
mask = a>25
print(a[mask])

[35 42 44]


In [80]:
print(a%4==0)

[False  True False  True  True  True False  True]


In [81]:
print(a[a%4==0])

[24 24 44 12  4]


In [ ]:
find the sum of all numbers which a divisible by 6 from
1 to 100

In [88]:
a = np.arange(1,101)
print(a[a%6==0])
print(np.sum(a[a%6==0]))

[ 6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96]
816


In [91]:
print(a[(a%6==0) & (a%4==0)])
print(np.sum(a[(a%6==0) & (a%4==0)]))

[12 24 36 48 60 72 84 96]
432


In [95]:
a = np.arange(1,2001)
print(max(a[a%13==0]))


1989


In [97]:
marks = np.random.randint(50,100,5)
print(marks)

[55 91 95 91 70]


In [99]:
res = np.where(marks>70,"PASS","FAIL")
print(res)

['FAIL' 'PASS' 'PASS' 'PASS' 'FAIL']


In [107]:
marks = np.random.randint(50,100,5)
print(marks)

[89 57 97 75 81]


In [108]:
res = np.where(marks>90,"A",
               np.where(marks>80,"B",
                np.where(marks>70,"C","D")))
print(res)

['B' 'D' 'A' 'C' 'B']


In [109]:
print(marks)

[89 57 97 75 81]


In [114]:
def grade(n):
    if n>90:return "A"
    elif n>80: return "B"
    elif n>70: return "C"
    else: return "D"
# res = np.vectorize(grade)(marks)
showgrade = np.vectorize(grade)
res =  showgrade(marks)
print(res)

['B' 'D' 'A' 'C' 'B']


In [119]:
names = np.array(["Vikram","Sid","Rahul","Jay","El"])
#output : ["Vikram","Rahul"]

In [125]:
# res = np.vectorize(len)(names)
# print(res)
# print(res>3)
# print(names[res>3])
print(names[np.vectorize(len)(names)>3])

['Vikram' 'Rahul']


In [126]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a.shape)

(9,)


In [128]:
b = a.reshape([3,3])
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [131]:
c= b.flatten()
print(c)

[1 2 3 4 5 6 7 8 9]
